### ISSUE TITLE
Can this be released separately?

### ISSUE THREAD

**Issue by CptSpaceToaster** [gildedgames/threaded-lighting#1]
I may not understand your setup, but it appears that this mod exists as a dependency for the Aether II mod.  I'm not sure how you guys package for release, but I was wondering if `threaded-lighting` is available as a stand alone mod?

Reason: It's compatible with the [ColoredLightCore](https://github.com/CptSpaceToaster/CptsModdingLight), and serves to split up lighting decently to a new thread...

Possible Issues: The Aether II may have to fuzz the list of loaded mods and change how it loads if `threaded-lighting` is already present as a standalone.

**Comment by HEmile** [comment]
Threaded Lighting is now a part of Gilded Games Util, which you can use separately of the Aether http://aetherii.com/downloads

**Comment by CptSpaceToaster** [comment]
Documentation on what Gilded Games Util actually contains/does would be appreciated :)

**Comment by Brenwwe** [comment]
Gilded Games Util contains core functionality that we use across all of our projects. It is a module which supports several major systems such as our tab-api system.

**Comment by CptSpaceToaster** [comment]
Which is great... but I don't want to have to go to git and figure out what's inside the jar...

The linked [website](http://aetherii.com/downloads) doesn't appear to offer much of a description, so users are basically just looking for a file names "Gilded Games Util"... without any idea what it is?

Or am I wrong, and this is documented somewhere?  I just want to know what I'm downloading, and why.  That way, I feel comfortable telling other people who are interested in maxing out CLC's performance about some of the work you guys have done!

**Comment by Collin1971** [comment]
haha, thanks. That's pretty much my doing. :)

As a whole, the Gilded Games Util JAR is a set of utilities that other mods can take advantage of, such as the Tab API, IO API, Player Hook API, or ThreadedLighting (although right now the only mod which uses it is the Aether II). Installing it doesn't change the game besides enabling Threaded Lighting.

As for documentation, there's very little if any. I can work on setting up a GitHub wiki with documentation for it over the weekend, though it might take a while.

**Comment by CptSpaceToaster** [comment]
As a user, I'd love it if you had something on your website, rather than Github... but that's just me. Linking something from the website to the github wiki would also accomplish the same thing.

Basically... if I go to download the mod (your website) I'd like to see what it is I'm downloading somewhere.  If that's a link away, that's cool.

You guys are awesome :)

Have a nice day.
